#!/usr/bin/python
import datafetch.searchbuilder
import sys
cache = datafetch.searchbuilder.Search(str(sys.argv[1]),str(sys.argv[2]))
cache.build_cache()
json = cache.get_cache().to_json()
lines = json.split('\n')
for line in lines:
	print line
