#!/usr/bin/python
import sys
import datafetch.searchbuilder
def GET():
	cache = datafetch.searchbuilder.Search(sys.argv[1],sys.argv[2])
	cache.build_cache()
	json = cache.get_cache().to_json()
	lines = json.split('\n')
	for line in lines:
			print line
			#print "<br>"


GET()
