#!/usr/bin/python
import sys
import cgi
import datafetch.searchbuilder
def GET():
	form = cgi.FieldStorage()
	print "Content-type:text/json\r\n\r\n"
	if "term" not in form:
		print '{ "error": "Please fill in term field." }'
		return
	elif "category" not in form:
		print '{ "error": "Please fill in category field." }'
		return
	else:
		
		buildCache = datafetch.searchbuilder.Search(str(form["term"].value),str(form["category"].value))
		buildCache.build_cache()
		cache = buildCache.get_cache()
		cache.de_duplicate_cache()
		cache.analyze_comments()
		json = cache.to_json()
		lines = json.split('\n')
		for line in lines:
			#spaces = 0
			#for i in line:
			#	if i == ' ':
			#		spaces += 1
			#	else:
			#		break
			#for i in range(0, spaces):
			#	print '&nbsp;'
			
						
			print line
			#print "<br>"


GET()
