#!/usr/bin/python
import sys
import cgi
import os
import datafetch.searchbuilder
def GET():
	form = cgi.FieldStorage()
	print "Content-type:text/html\r\n\r\n"
	if "term" not in form:
		print "<H1>Error</H1>"
		print "Please fill in term field."
		return
	elif "category" not in form:
		print "<H1>Error</H1>"
		print "Please fill in category field."
		return
	else:
		result = os.popen('proxychains ./RunSearch ' + form["term"].value + " " + form["category"])

GET()
