#! /bin/bash
	time ./testSearchBuilder.py > out.txt &
	time ./testSearchBuilder.py > out.txt &
	time ./testSearchBuilder.py > out.txt &
	time ./testSearchBuilder.py > out.txt &
	time ./testSearchBuilder.py > out.txt &
	time ./testSearchBuilder.py > out.txt &
