#!/usr/bin/python
import sys
import cgi
import json as jsobject
from search import searchbuilder
from search import searchcache
def GET():
        form = cgi.FieldStorage()
	print "Content-type:text/json\r\n\r\n"
	term = "in the end "
	category = "music"
	size = False
	buildcache = searchbuilder.Search(term, category)
	if size == True:
		print jsobject.dumps({"size":searchcache.get_size_by_hash(buildcache._hash_title_and_category())})

	else:
		
		if buildcache.check_in_cache():
			print searchcache.open_search_by_hash(buildcache._hash_title_and_category())
			buildcache.build_cache()	
		else:
			try:
				buildcache.build_cache()
				cache = buildcache.get_cache()
			except:
				print "{no results}"
				return
			if len(buildcache.get_cache()) == 0:
				print "{no results}"
			else:
				json = cache.to_json()
				lines = json.split('\n')
				for line in lines:
					print line


GET()
