#!/usr/bin/python
import sys
import cgi
from search import searchbuilder
from search import searchcache
def GET():
        form = cgi.FieldStorage()
	print "Content-type:text/json\r\n\r\n"
        if "term" not in form:
                print '{ "error": "Please fill in term field." }'
                return
        elif "category" not in form:
                print '{ "error": "Please fill in category field." }'
                return
        else:
		buildcache = searchbuilder.Search(str(form["term"].value),str(form["category"].value))
		#buildcache = datafetch.searchbuilder.Search("linkin park 4","music")
		if buildcache.check_in_cache():
			print searchcache.open_search_by_hash(buildcache._hash_title_and_category())

		else:
			buildcache.build_cache()
			cache = buildcache.get_cache()
			json = cache.to_json()
			lines = json.split('\n')
			for line in lines:
				print line


GET()
