#!/usr/bin/python
import sys
import cgi
import json as jsobject
from search import searchbuilder
from search import searchcache
from search import searchlog
def GET():
        form = cgi.FieldStorage()
	print "Content-type:text/json\r\n\r\n"
        if "term" not in form:
                print '{ "error": "Please fill in term field." }'
                return
        elif "category" not in form:
                print '{ "error": "Please fill in category field." }'
                return
        else:
		term = str(form["term"].value)
		category = str(form["category"].value)
		buildcache = searchbuilder.Search(term, category)
		searchlog.db_insert_log_entry(buildcache._hash_title_and_category(), term, category)
		if "getsize" in form:
			if str(form["getsize"].value).strip() == "true":
				print jsobject.dumps({"size":searchcache.db_get_size_by_hash(buildcache._hash_title_and_category())})
		else:
			
			if buildcache.check_in_cache():
				print searchcache.db_open_search_by_hash(buildcache._hash_title_and_category())
			else:
				try:
					buildcache.build_cache()
					cache = buildcache.get_cache()
					print cache.to_json()
				except:
					print '{"error": "no results"}'



GET()
